spring:
  application:
    name: mall

  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）// 3 号库存标签相关的数据
    database: 0
    # 连接超时时间（毫秒）
    timeout: 60000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      # 连接池中的最小空闲连接
    cluster:
      max-redirects: 10
      nodes: 127.0.0.1:6080
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
